<template>
  <div class="home-hero">
    <img src="../assets/sandpiper.jpg" alt="" aria-hidden="true" class="home-hero-image" />
    <section class="home-hero-inner">
      <span class="home-eyebrow">Public metagenome search</span>

      <h1 class="home-headline">{{ num_runs !== null ? num_runs.toLocaleString("en-US") : '••••••' }} metagenomes screened.</h1>
      <p class="home-subheadline">{{ num_terrabases !== null ? num_terrabases.toLocaleString("en-US") : '••••' }} Tbp across {{ num_bioprojects !== null ? num_bioprojects.toLocaleString("en-US") : '••••' }} projects</p>

      <p class="home-lede">Sandpiper {{ version }} is a resource for interrogating public shotgun metagenome datasets,
      presenting the results generated by <a href="https://github.com/wwood/singlem">SingleM</a>.</p>

      <p class="home-lede home-lede-muted">We gratefully acknowledge the large collective effort expended
      in administering, gathering, sequencing and uploading these datasets into the public domain.</p>

      <router-link to="/Search" class="button is-primary is-medium home-cta">
        Start exploring
        <span class="home-cta-icon" aria-hidden="true">
          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>
        </span>
      </router-link>
    </section>
  </div>
</template>

<script>
import { fetchSandpiperStats } from '@/api'
import { stopPageLoading } from '@/store/pageLoading'

export default {
  name: 'Home',
  title: 'Sandpiper',
  data: function () {
    return {
      num_terrabases: null,
      num_runs: null,
      num_bioprojects: null,
      version: null
    }
  },
  created () {
    // The template has no data gate -- the hero renders immediately with
    // placeholder numbers -- so this page is "loaded" as soon as it mounts.
    stopPageLoading()
    this.fetchData()
  },
  methods: {
    fetchData () {
      fetchSandpiperStats()
        .then(response => {
          const r = response.data
          this.num_terrabases = r.num_terrabases
          this.num_runs = r.num_runs
          this.num_bioprojects = r.num_bioprojects
          this.version = r.version
        })
    }
  },
  watch: {
    // call again the method if the route changes
    $route: 'fetchData'
  }
}
</script>

<style scoped>
.home-hero {
  position: relative;
  /* Capped, not just calc(100dvh - ...): on a taller monitor an uncapped
     viewport-height hero reveals more of the photo vertically, which shifts
     where the (off-center) bird ends up cropping into view -- that drift is
     what let the text overlap it on bigger screens despite looking fine on
     a laptop. Capping keeps the crop window closer to what it was tuned
     against. See .home-hero-inner for the other half of the fix. */
  min-height: min(calc(100dvh - 3.25rem), 800px);
  display: flex;
  /* Pinned to a fixed distance from the top (via .home-hero-inner's
     padding-top) instead of vertically centered -- centering ties the
     text's position to the hero's height, which is exactly what was
     drifting between screen sizes. A fixed offset from the top removes
     that dependency entirely rather than just capping it. */
  align-items: flex-start;
  overflow: hidden;
}
.home-hero-image {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  /* The source photo is itself very washed-out/low-contrast (a pale bird on
     pale water); a plain opacity overlay on top of that made it worse, so
     the fix is a contrast/saturation boost on the image itself, not the
     overlay on top of it. */
  filter: contrast(1.3) saturate(1.4) brightness(0.96);
  z-index: 0;
}
.home-hero-inner {
  position: relative;
  z-index: 1;
  max-width: 960px;
  margin: 0 auto 0 3%;
  padding: 3rem var(--space-8) var(--space-16);
}
.home-hero-inner::before {
  /* A soft, edgeless glow -- not a card/box, no border or radius to see --
     so text legibility no longer depends on the bird happening to land
     somewhere plain. This is the other half of the overlap fix: capping
     .home-hero's height keeps the drift small, this makes the remaining
     drift harmless regardless of screen size or aspect ratio. */
  content: '';
  position: absolute;
  inset: -10% -8%;
  z-index: -1;
  background: radial-gradient(ellipse 70% 65% at 32% 45%, rgba(250, 249, 246, 0.55) 0%, rgba(250, 249, 246, 0.28) 55%, rgba(250, 249, 246, 0) 80%);
}
.home-eyebrow {
  display: block;
  font-style: italic;
  font-size: 0.95rem;
  font-weight: 500;
  letter-spacing: 0.01em;
  color: hsl(174, 62%, 22%);
  margin-bottom: var(--space-6);
  text-shadow: 0 1px 6px rgba(250, 249, 246, 0.9), 0 1px 2px rgba(0, 0, 0, 0.12);
}
.home-headline {
  font-family: "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif;
  font-size: clamp(2.25rem, 1.6rem + 3vw, 3.75rem);
  line-height: 1.05;
  font-weight: 700;
  letter-spacing: -0.01em;
  margin: 0 0 var(--space-3);
  text-shadow: 0 1px 24px rgba(250, 249, 246, 0.9), 0 1px 3px rgba(250, 249, 246, 0.9), 0 2px 4px rgba(0, 0, 0, 0.15);
}
.home-subheadline {
  font-size: 1.1rem;
  font-weight: 600;
  color: hsl(0, 0%, 18%);
  margin-bottom: var(--space-8);
  text-shadow: 0 1px 16px rgba(250, 249, 246, 0.9), 0 1px 3px rgba(0, 0, 0, 0.12);
}
.home-lede {
  font-size: 1rem;
  font-weight: 500;
  line-height: 1.65;
  max-width: 45ch;
  margin-bottom: var(--space-4);
  text-shadow: 0 1px 16px rgba(250, 249, 246, 0.85), 0 1px 2px rgba(0, 0, 0, 0.1);
}
.home-lede-muted {
  color: hsl(0, 0%, 32%);
}
.home-cta {
  margin-top: var(--space-8);
  border-radius: 999px;
  padding-inline: var(--space-6);
  display: inline-flex;
  align-items: center;
  gap: var(--space-3);
}
.home-cta-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 1.6rem;
  height: 1.6rem;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.22);
  transition: transform 220ms cubic-bezier(0.32, 0.72, 0, 1);
}
.home-cta-icon svg {
  display: block;
}
.home-cta:hover .home-cta-icon {
  transform: translateX(2px);
}

@media (max-width: 768px) {
  .home-hero {
    /* Not full-viewport (so the hero doesn't force a fixed screen-height on
       phones), but not bare "auto" either -- that let the hero collapse to
       almost nothing while the stats API call is in flight (no numbers yet
       means very little text), which visibly dumped the footer mid-screen
       until the real numbers loaded and the page jumped. This keeps a
       reasonable floor so that jump doesn't happen. */
    min-height: 70vh;
  }
  .home-hero-inner {
    margin: 0 auto;
    padding: var(--space-12) var(--space-4);
  }
}
</style>
